### ISSUE TITLE
find file, file list doesn't use last few lines

### ISSUE THREAD

**Issue by thegaryking** [IQSS/IQSS.emacs#6] opened 2017-12-31 14:39 UTC
![image](https://user-images.githubusercontent.com/575230/34462291-5dcc4636-ee0e-11e7-913c-366786234e62.png)

can you get find file to use the remaining space at the bottom of this screen clip?

**Comment by izahn** [comment] 2018-01-02 19:33
It probably will not surprise you to learn that I can't reproduce this problem. Does it happen every time?

**Comment by thegaryking** [comment] 2018-01-02 19:54
no, not every time

Gary
--
*Gary King* - Albert J. Weatherhead III University Professor - Director,
IQSS <http://iq.harvard.edu/> - Harvard University
GaryKing.org - King@Harvard.edu - @KingGary <https://twitter.com/kinggary> -
617-500-7570 - Assistant <king-assist@iq.harvard.edu>: 617-495-9271

**Comment by izahn** [comment] 2018-01-27 02:09
I'm closing this for now since I can't reproduce it. If the problem persists please re-open this issue.

**Closed as completed** 2018-01-27 02:09 UTC
